version: '3'

services:
  server:
    build: server/
    command: python server.py
    ports:
      - 65432:65432
    extra_hosts:
      - "127.0.0.1:80:80"

  client:
    build: client/
    command: python client.py

    network_mode: host
